export { type InformValue, type IntInformValue, type StringInformValue, type ArrayInformValue, type ByteArrayInformValue, type RoutineInformValue, type PropertyAddressInformValue, type DictWordInformValue, intValue, stringValue, routineValue, dictWordValue, toInt, isTruthy, ivAdd, ivSub, ivMul, ivDiv, ivMod, } from './values/inform-value.js';
export { type PropertyValue, type IntPropertyValue, type StringPropertyValue, type ListPropertyValue, type DictWordPropertyValue, type RoutinePropertyValue, intPropValue, stringPropValue, propToScalarInt, propToInformValue, informValueToProp, propertyValueEquals, } from './values/property-value.js';
export { InformArray, type ArrayType } from './values/inform-array.js';
export { PersistentMap } from './values/persistent-map.js';
export { PersistentSet } from './values/persistent-set.js';
export { ObjectIdMapper } from './mappers/object-id-mapper.js';
export { AttributeMapper } from './mappers/attribute-mapper.js';
export { PropertyMapper } from './mappers/property-mapper.js';
export { Variables } from './state/variables.js';
export { ObjectTreeState } from './state/object-tree-state.js';
export { type GameState, createInitialGameState, setGlobal, getGlobal, setGlobalProp, getGlobalProp, toStringId, getParent, getChild, getSibling, registerObject, moveObject, removeFromParent, setAttribute, clearAttribute, hasAttribute, hasAttributeByIndex, safeGetProperty, getPropertyAsInformValue, setProperty, provides, isIn, isOfClass, getPropertyAddress, getPropertyLength, getPropertyWordAt, getPropertyByteAt, setPropertyWordAt, setPropertyByteAt, classCreate, pushStack, popStack, nextRandom, getArrayByAddress, getWordAtRawAddress, getByteAtRawAddress, setByteInArray, setWordInArray, setByteAtAddress, setWordAtByteOffset, } from './state/game-state.js';
export { type GameDefinition, createGameDefinition, } from './state/game-definition.js';
export { populateZMachineHeader } from './state/zmachine-header.js';
export { Dictionary } from './objects/dictionary.js';
export { type ObjectDefinition } from './objects/object-definition.js';
export { type GameIO, type Glk } from './io/game-io.js';
export { StringGameIO } from './io/string-game-io.js';
export { GameQuitError, GameRestartError, UndoRestoredError } from './io/exceptions.js';
export { type TextStyle, type StyledCell, type StyledRun, ROMAN_STYLE, EMPTY_CELL, applyStyleName, textStyleEquals, glkStyleToInform6StyleName, } from './io/text-style.js';
export { type OutputEvent, type PrintEvent, type PrintCharEvent, type PrintLineEvent, type ClearEvent, type SetCursorEvent, type SetWindowEvent, type SplitWindowEvent, type SetColorEvent, type SetFontEvent, type SetStyleEvent, type InputRequest, type LineInputRequest, type CharInputRequest, type NoInputRequest, type TurnResult, } from './io/output-event.js';
export { type StateDelta, type ObjectDelta, computeStateDelta, applyStateDelta, isStateDeltaEmpty, } from './history/state-delta.js';
export { type GameHistory, createGameHistory, pushState, undo, redo, } from './history/game-history.js';
export { type StateManager, createStateManager, saveUndo, restoreUndo, } from './history/state-manager.js';
export { type SerializedGameState, serializeState, deserializeState, serializeStateToJson, deserializeStateFromJson, } from './serialization/state-serializer.js';
export { type GameViewModel, type NavigationExit, type ExaminableTarget, type TargetLocation, type InputContext, type InventoryItem, deriveGameViewModel, } from './viewmodel/game-view-model.js';
export { type DirectionInfo, DIRECTION_TABLE } from './viewmodel/direction-map.js';
export { type GameWorldState, type GameStatus, type Direction, type RoomInfo, type ExitInfo, type ObjectAttributes, type ObjectInfo, type NpcInfo, } from './extraction/game-world-state.js';
export { extractGameWorldState } from './extraction/extract-game-world-state.js';
